golemfactory/gamerhash-facade

.gitignore, .vscode/launch.json, Golem/Yagna/Provider.cs, GolemLib.sln, MockGUI/App.axaml, MockGUI/App.axaml.cs, MockGUI/GolemModel.cs, MockGUI/MainWindow.axaml, MockGUI/MainWindow.axaml.cs, MockGUI/MockGUI.csproj, MockGUI/Program.cs, MockGUI/app.manifest, MockGUI/readme.md
resolves: https://github.com/golemfactory/ya-runtime-ai/issues/10
=> Avalonia facade tester gui

Golem/Golem.cs, Golem/Yagna/ProcessFactory.cs, Golem/Yagna/YagnaService.cs
+ Fix waiting for process start
=> Setup directories

Golem.Tools/SampleApp.cs, MockGUI/GolemModel.cs, MockGUI/MainWindow.axaml
partially resolves: https://github.com/golemfactory/ya-runtime-ai/issues/20
=> Single object for managing example

.vscode/launch.json, Golem.Tests/JobTests.cs, Golem.Tools/GolemRelay.cs, Golem.Tools/GolemRequestor.cs, Golem/ActivityLoop.cs, Golem/Jobs.cs, Golem/Yagna/Model/ActivityStatePair.cs, Golem/Yagna/Provider.cs, MockGUI/App.axaml.cs, MockGUI/GolemModel.cs
Resolves: https://github.com/golemfactory/ya-runtime-ai/issues/28
=> Activity status api query

Golem/Yagna/EnvironmentBuilder.cs
Uses: https://github.com/golemfactory/yagna/pull/2948
=> Set env to disable Offers ban (works only in not published yet yagna)

Golem.Tests/JobTests.cs, Golem.Tools/App/app.py, Golem.Tools/GolemPackageBuilder.cs, Golem/Jobs.cs, Golem/Yagna/EnvironmentBuilder.cs, MockGUI/readme.md
resolves: https://github.com/golemfactory/ya-runtime-ai/issues/16
First version of working model deploy.
Doesn't solve problem `Downloaded VM image corrupted`.
=> Deploy model

.github/workflows/tests.yml, .vscode/launch.json, Golem.Package/Args.cs, Golem.Tests/GlobalUsings.cs, Golem.Tests/GolemTests.cs, Golem.Tests/JobTests.cs, Golem.Tests/xunit.runner.json, Golem.Tools/App/app.py, Golem.Tools/GolemPackageBuilder.cs, Golem.Tools/GolemRequestor.cs, Golem.Tools/SampleApp.cs, Golem/Golem.cs, Golem/Golem.csproj, Golem/Tools/ChildProcessTracker.cs, Golem/Yagna/PresetConfigService.cs, Golem/Yagna/ProcessFactory.cs, Golem/Yagna/Provider.cs, Golem/Yagna/ProviderConfigService.cs, Golem/Yagna/YagnaOptionsFactory.cs, Golem/Yagna/YagnaService.cs, Golem/Yagna/types.cs, MockGUI/readme.md, modules.sh
Resolves: https://github.com/golemfactory/ya-runtime-ai/issues/23
=> Multiple runtimes support. Graceful shutdown of Golem processes.

.gitignore, .vscode/launch.json, Golem.Package/Program.cs, Golem.Tests/GlobalUsings.cs, Golem.Tests/Golem.IntegrationTests.csproj, Golem.Tests/GolemTests.cs, Golem.Tests/JobTests.cs, Golem.Tests/PresetConfigServiceTests.cs, Golem.Tools/GolemRelay.cs, Golem/ActivityLoop.cs, Golem/Golem.cs, Golem/Jobs.cs, Golem/Yagna/PresetConfigService.cs, Golem/Yagna/ProcessFactory.cs, Golem/Yagna/Provider.cs, Golem/Yagna/YagnaService.cs
Resolves: https://github.com/golemfactory/ya-runtime-ai/issues/37
=> Process handling / multiple presets bugfixes

Golem.Package/Args.cs, Golem.Tools/GolemPackageBuilder.cs, MockGUI/readme.md
Resolves: https://github.com/golemfactory/ya-runtime-ai/issues/40
=> Processes shutdown issues

.gitignore, Golem.Tests/Golem.IntegrationTests.csproj, Golem.Tests/GolemTests.cs, Golem.Tools/GolemRelay.cs, Golem/Yagna/PresetConfigService.cs, Golem/Yagna/ProcessFactory.cs, Golem/Yagna/Provider.cs, Golem/Yagna/ProviderConfigService.cs, Golem/Yagna/YagnaService.cs, Readme.md, example/ai-requestor/.env, example/ai-requestor/README.md, example/ai-requestor/ai_runtime.py, scripts/automatic.ps1, scripts/config.json, scripts/ya-automatic-ai.json
- Initialization of default presets on get GolemPrices when Provider stopped.
- Unification preset prices on GolemPrice get
- Script for building dist package w Automatic
- Readme update about ^ script
=> Init presets before start

Golem.Tools/GolemRelay.cs, Golem/ActivityLoop.cs, Golem/Golem.cs, Golem/InvoiceEventsLoop.cs, MockGUI/Converters.cs, MockGUI/MainWindow.axaml
resolves: https://github.com/golemfactory/gamerhash-facade/issues/44
=> Display payment confirmation

MockGUI/Converters.cs, MockGUI/MainWindow.axaml, MockGUI/MockGUI.csproj
- Display recovered NodeId and PubKey
- Fix signatures validation
- Change Keccak256 to Sha3_256
- Compare Payment.PayerId with address recovered from signature
=> Fix signatures validation

Golem.Tests/GolemTests.cs, Golem.Tests/JobTests.cs, Golem.Tests/PropertyChangeTests.cs, Golem.Tests/StartStopTests.cs, Golem.Tools/GolemPackageBuilder.cs, Golem.Tools/PropertyChangedHandler.cs, Golem/Golem.cs, Golem/Yagna/ProcessFactory.cs, Golem/Yagna/Provider.cs, Golem/Yagna/YagnaService.cs
resolves: https://github.com/golemfactory/ya-runtime-ai/issues/54
should resolve: https://github.com/golemfactory/gamerhash-facade/issues/78 as well
=> Rework starting and stopping functionality

Golem.Package/Args.cs, Golem.Tools/GolemPackageBuilder.cs, MockGUI/readme.md
Tag `v2.0.0` https://github.com/golemfactory/gamerhash-facade/releases
=> Release 2.0.x

Golem/Jobs.cs
Resolves: https://github.com/golemfactory/gamerhash-facade/issues/96
=> Payments confirmation updates for any status

Golem.Package/Args.cs, Golem.Tools/GolemPackageBuilder.cs, MockGUI/readme.md
Resolves: https://github.com/golemfactory/ya-runtime-ai/issues/88
=> no GPU detection for dummy runtime

Golem.Tests/StartStopTests.cs, Golem.Tests/Utils.cs, Golem/Factory.cs, GolemLib/IFactory.cs
Resolves: https://github.com/golemfactory/gamerhash-facade/issues/87
=> Configurable data dir

Golem/Yagna/YagnaApi.cs
Warning! This has to wait for https://github.com/golemfactory/yagna/pull/3154
=> timeout changes were reverted

Golem.Package/Args.cs, Golem.Tests/ErrorHandlingTests.cs, Golem.Tests/GlobalUsings.cs, Golem.Tests/Golem.IntegrationTests.csproj, Golem.Tests/JobTests.cs, Golem.Tests/ProviderFailureHandlingTest.cs, Golem.Tests/StartStopTests.cs, Golem.Tests/Utils.cs, Golem.Tools/GolemPackageBuilder.cs, Golem/Golem.cs, MockGUI/readme.md
Resolves: https://github.com/golemfactory/gamerhash-facade/issues/111
=> Transition from status Error to Off

Golem.Tools/App/app.py, example/ai-requestor/ai_runtime.py
Resolves https://github.com/golemfactory/ya-runtime-ai/issues/53
=> update gsb proxy path

Golem/ActivityLoop.cs, Golem/EventsPublisher.cs, Golem/Golem.cs, Golem/InvoiceEventsLoop.cs, Golem/Yagna/Provider.cs, Golem/Yagna/YagnaApi.cs, Golem/Yagna/YagnaService.cs, GolemLib/IGolem.cs, GolemLib/types.cs, MockGUI/GolemModel.cs, MockGUI/MainWindow.axaml
=> Events for exceptions

Golem.Package/Args.cs, Golem.Tools/GolemPackageBuilder.cs, MockGUI/readme.md, scripts/automatic.ps1, scripts/ya-automatic-ai.json
Resolves: https://github.com/golemfactory/gamerhash-facade/issues/142
=> Automatic 0.1.3 and runtime startup handling improvement

.github/workflows/tests.yml, Golem.Package/Args.cs, Golem.Tests/ErrorHandlingTest.cs, Golem.Tests/JobStatusTests.cs, Golem.Tests/JobTests.cs, Golem.Tests/Utils.cs, Golem.Tools/GolemPackageBuilder.cs, Golem.Tools/GolemRequestor.cs, Golem.Tools/GolemRunnable.cs, Golem.Tools/SampleApp.cs, Golem/ActivityLoop.cs, Golem/EventsPublisher.cs, Golem/Golem.cs, Golem/Golem.csproj, Golem/InvoiceEventsLoop.cs, Golem/Jobs.cs, Golem/Testing.cs, Golem/Tools/JsonSerializerOptionsBuilder.cs, Golem/Yagna/Job.cs, Golem/Yagna/Model/YagnaAgreement.cs, Golem/Yagna/Model/YagnaAgreementInfo.cs, Golem/Yagna/Provider.cs, Golem/Yagna/YagnaApi.cs, Golem/Yagna/YagnaService.cs, GolemLib/types.cs, MockGUI/readme.md, example/ai-requestor/ai_runtime.py
resolves: https://github.com/golemfactory/gamerhash-facade/issues/152
resolves: https://github.com/golemfactory/gamerhash-facade/issues/118
resolves: https://github.com/golemfactory/gamerhash-facade/issues/150
=> Job statuses tests

Golem/Yagna/EnvironmentBuilder.cs, Golem/Yagna/Provider.cs
> [!IMPORTANT]  
> Change base to master before merging
resolves: https://github.com/golemfactory/gamerhash-facade/issues/169
=> Reduce amount of logs

Golem/Yagna/ProcessFactory.cs, Golem/Yagna/ProviderRulesService.cs
resolves: https://github.com/golemfactory/modelserve-support-triage/issues/2
=> Fix issues related to cert path containing spaces

.github/workflows/release.yml, scripts/automatic.ps1
TODO: replace AWS keys before the merge
=> Migrate to the production account S3 bucket
